### ISSUE TITLE
Editing entry on completed list fills "finish date" with current date

### ISSUE THREAD

**Issue by LitDub** [danejur/AniDroid#4]
When editing any entry on the completed list which has no finish date, the finish date gets automatically filled with the current date.

Also, when editing any entry on the "Reading" or "Watching" lists which have no *start* date, that also gets filled in with the current date.

**Comment by danejur** [comment]
I'm going to take a look at this. Right now, I have AniDroid automatically filling in the dates when you edit the list item (end date for "completed" and start date for "current"). I'm going to add a setting that disables this functionality (so that the fields will remain blank when you set those statuses).

HOWEVER: I am fairly certain that AniList itself is assigning the end date automatically when adding a list item with the "completed" status (even if it appears blank in AniDroid). I will have to research this a bit more.

**Comment by danejur** [comment]
Fixed in 05af923e081024f71c71bda8d39e126e57885970
